/**
 * Organizaciones predefinidas — nombres canónicos, ordenados alfabéticamente.
 * Deben coincidir exactamente con los valores normalizados en DynamoDB.
 */

export const PREDEFINED_ORGANIZATIONS = [
  'AAPEDS - Río Piedras',
  'AESA - Ciencias Médicas',
  'AESPUG - RCM',
  'ACS - UPRRP',
  'AEC UPR - Cayey',
  'AEC UPR - Humacao',
  'AMSA UPR - Bayamón',
  'AMSA UPR - Cayey',
  'AMSA UPR - Río Piedras',
  'AMSA Universidad Interamericana Metro',
  'AMWA UPR - Río Piedras',
  'APPR - Río Piedras',
  'Acción Social desde la Psicología UPR Río Piedras',
  'Ana G Méndez de Gurabo',
  'Baristas del Caribe (Starbucks) - Los Colobos, Carolina',
  'CASHI',
  'CGE',
  'CPM - UPR Mayagüez',
  'CUDAS UPR - Cayey',
  'Capítulo Hortus - NHS',
  'Capítulo Hortus de University Gardens',
  'Colegio de La Salle',
  'Cupeyville School',
  'DECA UAGM Cupey',
  'Doce25',
  'Escuela Pedro Falú Orellano',
  'Escuela Segundo Ruiz Belvis',
  'FPA UPR - Bayamón',
  'FPA UPR - Cayey',
  'FPA - UPRRP',
  'GOSA - UPRRP',
  'HOSA - UPRRP',
  'Hortus',
  'IQ Dermos UPR - Río Piedras',
  'IRP+',
  'MAPFRE',
  'MedLife Inter Metro',
  'MedLife Interamericana',
  'MedLife UAGM - Gurabo',
  'MedLife UIPR Metro',
  'MedLife UPR - Cayey',
  'MedLife UPR - Río Piedras',
  'Neuroboricuas UPR - Arecibo',
  'Neuroboricuas UPR - Bayamón',
  'Neuroboricuas UPR - Río Piedras',
  'Organización de las Naciones Unidas (ONU)',
  'PRPDA UPR - Río Piedras',
  'PRPDA Intermetro',
  'PSYCHI UPR - Cayey',
  'PVSA - UPRRP',
  'Planet Guardians',
  'Pre Vet Student Association Río Piedras',
  'Pre-Law UPR - Cayey',
  'SACNAS UPR - Río Piedras',
  'Sociedad de Honor Junior - Fidei',
  'Sociedad Eco-Ambiental UPRRP',
  'TMED UPR - Cayey',
  'Tribeta UPR - Cayey',
  'University Gardens High School',
  'Vet-Tech Community UAGM - Gurabo',
  'WINS UPR - Río Piedras',
]

export const getDefaultOrganizations = (): string[] => {
  return [...PREDEFINED_ORGANIZATIONS]
}
